### PR TITLE
Adding tests for the `fileName` property

### PR DESCRIPTION
**Pull request by arthurvr**

### CODE REVIEW

**Comment by arthurvr** [comment]
cc @crswll as an fyi

**Comment by sukima** [comment]
I don't see a down side to this PR. :shipit:

**Comment by arthurvr** [comment]
@sukima @crswll Maybe one has a little of time to write tests for the `formats` option?

**Comment by crswll** [comment]
I'll write that test.

**Comment by crswll** [comment]
I wrote the test, it passed and I merges it with master and committed it. Hopefully I did that all properly.

**Pull request merged**
